image: gitpod/workspace-node:latest
tasks:
  - init: npm install
    command: echo "Environment ready! use npm test to run tests."
ports:
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - hbenl.vscode-mocha-test-adapter
    - ryanluker.vscode-coverage-gutters
    - ms-vscode.vscode-typescript-next
